/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as RelogiosRouteImport } from './routes/relogios'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social/index'
import { Route as SocialEntrarRouteImport } from './routes/social_.entrar'
import { Route as SocialRelatoriosRouteImport } from './routes/social/relatorios'
import { Route as SocialRelacionamentoRouteImport } from './routes/social/relacionamento'
import { Route as SocialPublicacoesRouteImport } from './routes/social/publicacoes'
import { Route as SocialImpulsionamentosRouteImport } from './routes/social/impulsionamentos'
import { Route as SocialHistoricoRouteImport } from './routes/social/historico'
import { Route as SocialGeralRouteImport } from './routes/social/geral'
import { Route as SocialEquipeRouteImport } from './routes/social/equipe'
import { Route as SocialContasRouteImport } from './routes/social/contas'
import { Route as SocialAtualizarRouteImport } from './routes/social/atualizar'
import { Route as RelatorioTokenRouteImport } from './routes/relatorio.$token'
import { Route as OauthRetornoRouteImport } from './routes/oauth.retorno'
import { Route as SocialPublicacaoPostIdRouteImport } from './routes/social/publicacao.$postId'
import { Route as SocialContaAccountIdRouteImport } from './routes/social/conta.$accountId'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const RelogiosRoute = RelogiosRouteImport.update({
  id: '/relogios',
  path: '/relogios',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SocialRoute,
} as any)
const SocialEntrarRoute = SocialEntrarRouteImport.update({
  id: '/social_/entrar',
  path: '/social/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRelatoriosRoute = SocialRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => SocialRoute,
} as any)
const SocialRelacionamentoRoute = SocialRelacionamentoRouteImport.update({
  id: '/relacionamento',
  path: '/relacionamento',
  getParentRoute: () => SocialRoute,
} as any)
const SocialPublicacoesRoute = SocialPublicacoesRouteImport.update({
  id: '/publicacoes',
  path: '/publicacoes',
  getParentRoute: () => SocialRoute,
} as any)
const SocialImpulsionamentosRoute = SocialImpulsionamentosRouteImport.update({
  id: '/impulsionamentos',
  path: '/impulsionamentos',
  getParentRoute: () => SocialRoute,
} as any)
const SocialHistoricoRoute = SocialHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => SocialRoute,
} as any)
const SocialGeralRoute = SocialGeralRouteImport.update({
  id: '/geral',
  path: '/geral',
  getParentRoute: () => SocialRoute,
} as any)
const SocialEquipeRoute = SocialEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => SocialRoute,
} as any)
const SocialContasRoute = SocialContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => SocialRoute,
} as any)
const SocialAtualizarRoute = SocialAtualizarRouteImport.update({
  id: '/atualizar',
  path: '/atualizar',
  getParentRoute: () => SocialRoute,
} as any)
const RelatorioTokenRoute = RelatorioTokenRouteImport.update({
  id: '/relatorio/$token',
  path: '/relatorio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRetornoRoute = OauthRetornoRouteImport.update({
  id: '/oauth/retorno',
  path: '/oauth/retorno',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPublicacaoPostIdRoute = SocialPublicacaoPostIdRouteImport.update({
  id: '/publicacao/$postId',
  path: '/publicacao/$postId',
  getParentRoute: () => SocialRoute,
} as any)
const SocialContaAccountIdRoute = SocialContaAccountIdRouteImport.update({
  id: '/conta/$accountId',
  path: '/conta/$accountId',
  getParentRoute: () => SocialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/programacao': typeof ProgramacaoRoute
  '/radio': typeof RadioRoute
  '/relogios': typeof RelogiosRoute
  '/social': typeof SocialRouteWithChildren
  '/oauth/retorno': typeof OauthRetornoRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/social/atualizar': typeof SocialAtualizarRoute
  '/social/contas': typeof SocialContasRoute
  '/social/equipe': typeof SocialEquipeRoute
  '/social/geral': typeof SocialGeralRoute
  '/social/historico': typeof SocialHistoricoRoute
  '/social/impulsionamentos': typeof SocialImpulsionamentosRoute
  '/social/publicacoes': typeof SocialPublicacoesRoute
  '/social/relacionamento': typeof SocialRelacionamentoRoute
  '/social/relatorios': typeof SocialRelatoriosRoute
  '/social/entrar': typeof SocialEntrarRoute
  '/social/': typeof SocialIndexRoute
  '/social/conta/$accountId': typeof SocialContaAccountIdRoute
  '/social/publicacao/$postId': typeof SocialPublicacaoPostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/programacao': typeof ProgramacaoRoute
  '/radio': typeof RadioRoute
  '/relogios': typeof RelogiosRoute
  '/oauth/retorno': typeof OauthRetornoRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/social/atualizar': typeof SocialAtualizarRoute
  '/social/contas': typeof SocialContasRoute
  '/social/equipe': typeof SocialEquipeRoute
  '/social/geral': typeof SocialGeralRoute
  '/social/historico': typeof SocialHistoricoRoute
  '/social/impulsionamentos': typeof SocialImpulsionamentosRoute
  '/social/publicacoes': typeof SocialPublicacoesRoute
  '/social/relacionamento': typeof SocialRelacionamentoRoute
  '/social/relatorios': typeof SocialRelatoriosRoute
  '/social/entrar': typeof SocialEntrarRoute
  '/social': typeof SocialIndexRoute
  '/social/conta/$accountId': typeof SocialContaAccountIdRoute
  '/social/publicacao/$postId': typeof SocialPublicacaoPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/biblioteca': typeof BibliotecaRoute
  '/programacao': typeof ProgramacaoRoute
  '/radio': typeof RadioRoute
  '/relogios': typeof RelogiosRoute
  '/social': typeof SocialRouteWithChildren
  '/oauth/retorno': typeof OauthRetornoRoute
  '/relatorio/$token': typeof RelatorioTokenRoute
  '/social/atualizar': typeof SocialAtualizarRoute
  '/social/contas': typeof SocialContasRoute
  '/social/equipe': typeof SocialEquipeRoute
  '/social/geral': typeof SocialGeralRoute
  '/social/historico': typeof SocialHistoricoRoute
  '/social/impulsionamentos': typeof SocialImpulsionamentosRoute
  '/social/publicacoes': typeof SocialPublicacoesRoute
  '/social/relacionamento': typeof SocialRelacionamentoRoute
  '/social/relatorios': typeof SocialRelatoriosRoute
  '/social_/entrar': typeof SocialEntrarRoute
  '/social/': typeof SocialIndexRoute
  '/social/conta/$accountId': typeof SocialContaAccountIdRoute
  '/social/publicacao/$postId': typeof SocialPublicacaoPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/biblioteca'
    | '/programacao'
    | '/radio'
    | '/relogios'
    | '/social'
    | '/oauth/retorno'
    | '/relatorio/$token'
    | '/social/atualizar'
    | '/social/contas'
    | '/social/equipe'
    | '/social/geral'
    | '/social/historico'
    | '/social/impulsionamentos'
    | '/social/publicacoes'
    | '/social/relacionamento'
    | '/social/relatorios'
    | '/social/entrar'
    | '/social/'
    | '/social/conta/$accountId'
    | '/social/publicacao/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/biblioteca'
    | '/programacao'
    | '/radio'
    | '/relogios'
    | '/oauth/retorno'
    | '/relatorio/$token'
    | '/social/atualizar'
    | '/social/contas'
    | '/social/equipe'
    | '/social/geral'
    | '/social/historico'
    | '/social/impulsionamentos'
    | '/social/publicacoes'
    | '/social/relacionamento'
    | '/social/relatorios'
    | '/social/entrar'
    | '/social'
    | '/social/conta/$accountId'
    | '/social/publicacao/$postId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/biblioteca'
    | '/programacao'
    | '/radio'
    | '/relogios'
    | '/social'
    | '/oauth/retorno'
    | '/relatorio/$token'
    | '/social/atualizar'
    | '/social/contas'
    | '/social/equipe'
    | '/social/geral'
    | '/social/historico'
    | '/social/impulsionamentos'
    | '/social/publicacoes'
    | '/social/relacionamento'
    | '/social/relatorios'
    | '/social_/entrar'
    | '/social/'
    | '/social/conta/$accountId'
    | '/social/publicacao/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  RadioRoute: typeof RadioRoute
  RelogiosRoute: typeof RelogiosRoute
  SocialRoute: typeof SocialRouteWithChildren
  OauthRetornoRoute: typeof OauthRetornoRoute
  RelatorioTokenRoute: typeof RelatorioTokenRoute
  SocialEntrarRoute: typeof SocialEntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relogios': {
      id: '/relogios'
      path: '/relogios'
      fullPath: '/relogios'
      preLoaderRoute: typeof RelogiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social_/entrar': {
      id: '/social_/entrar'
      path: '/social/entrar'
      fullPath: '/social/entrar'
      preLoaderRoute: typeof SocialEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/relatorios': {
      id: '/social/relatorios'
      path: '/relatorios'
      fullPath: '/social/relatorios'
      preLoaderRoute: typeof SocialRelatoriosRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/relacionamento': {
      id: '/social/relacionamento'
      path: '/relacionamento'
      fullPath: '/social/relacionamento'
      preLoaderRoute: typeof SocialRelacionamentoRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/publicacoes': {
      id: '/social/publicacoes'
      path: '/publicacoes'
      fullPath: '/social/publicacoes'
      preLoaderRoute: typeof SocialPublicacoesRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/impulsionamentos': {
      id: '/social/impulsionamentos'
      path: '/impulsionamentos'
      fullPath: '/social/impulsionamentos'
      preLoaderRoute: typeof SocialImpulsionamentosRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/historico': {
      id: '/social/historico'
      path: '/historico'
      fullPath: '/social/historico'
      preLoaderRoute: typeof SocialHistoricoRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/geral': {
      id: '/social/geral'
      path: '/geral'
      fullPath: '/social/geral'
      preLoaderRoute: typeof SocialGeralRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/equipe': {
      id: '/social/equipe'
      path: '/equipe'
      fullPath: '/social/equipe'
      preLoaderRoute: typeof SocialEquipeRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/contas': {
      id: '/social/contas'
      path: '/contas'
      fullPath: '/social/contas'
      preLoaderRoute: typeof SocialContasRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/atualizar': {
      id: '/social/atualizar'
      path: '/atualizar'
      fullPath: '/social/atualizar'
      preLoaderRoute: typeof SocialAtualizarRouteImport
      parentRoute: typeof SocialRoute
    }
    '/relatorio/$token': {
      id: '/relatorio/$token'
      path: '/relatorio/$token'
      fullPath: '/relatorio/$token'
      preLoaderRoute: typeof RelatorioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/retorno': {
      id: '/oauth/retorno'
      path: '/oauth/retorno'
      fullPath: '/oauth/retorno'
      preLoaderRoute: typeof OauthRetornoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/publicacao/$postId': {
      id: '/social/publicacao/$postId'
      path: '/publicacao/$postId'
      fullPath: '/social/publicacao/$postId'
      preLoaderRoute: typeof SocialPublicacaoPostIdRouteImport
      parentRoute: typeof SocialRoute
    }
    '/social/conta/$accountId': {
      id: '/social/conta/$accountId'
      path: '/conta/$accountId'
      fullPath: '/social/conta/$accountId'
      preLoaderRoute: typeof SocialContaAccountIdRouteImport
      parentRoute: typeof SocialRoute
    }
  }
}

interface SocialRouteChildren {
  SocialAtualizarRoute: typeof SocialAtualizarRoute
  SocialContasRoute: typeof SocialContasRoute
  SocialEquipeRoute: typeof SocialEquipeRoute
  SocialGeralRoute: typeof SocialGeralRoute
  SocialHistoricoRoute: typeof SocialHistoricoRoute
  SocialImpulsionamentosRoute: typeof SocialImpulsionamentosRoute
  SocialPublicacoesRoute: typeof SocialPublicacoesRoute
  SocialRelacionamentoRoute: typeof SocialRelacionamentoRoute
  SocialRelatoriosRoute: typeof SocialRelatoriosRoute
  SocialIndexRoute: typeof SocialIndexRoute
  SocialContaAccountIdRoute: typeof SocialContaAccountIdRoute
  SocialPublicacaoPostIdRoute: typeof SocialPublicacaoPostIdRoute
}

const SocialRouteChildren: SocialRouteChildren = {
  SocialAtualizarRoute: SocialAtualizarRoute,
  SocialContasRoute: SocialContasRoute,
  SocialEquipeRoute: SocialEquipeRoute,
  SocialGeralRoute: SocialGeralRoute,
  SocialHistoricoRoute: SocialHistoricoRoute,
  SocialImpulsionamentosRoute: SocialImpulsionamentosRoute,
  SocialPublicacoesRoute: SocialPublicacoesRoute,
  SocialRelacionamentoRoute: SocialRelacionamentoRoute,
  SocialRelatoriosRoute: SocialRelatoriosRoute,
  SocialIndexRoute: SocialIndexRoute,
  SocialContaAccountIdRoute: SocialContaAccountIdRoute,
  SocialPublicacaoPostIdRoute: SocialPublicacaoPostIdRoute,
}

const SocialRouteWithChildren =
  SocialRoute._addFileChildren(SocialRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BibliotecaRoute: BibliotecaRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  RadioRoute: RadioRoute,
  RelogiosRoute: RelogiosRoute,
  SocialRoute: SocialRouteWithChildren,
  OauthRetornoRoute: OauthRetornoRoute,
  RelatorioTokenRoute: RelatorioTokenRoute,
  SocialEntrarRoute: SocialEntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
